version: '3.6'

services:
  traefik:
    image: traefik:latest
    restart: always
    ports:
      - 80:80
      - 443:443
#      - 8080:8080
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik-conf/traefik.toml:/traefik.toml
      - ./traefik-conf/acme.json:/acme.json

networks:
  proxy:
    external: true

