version: "3.6"

services:
  whoami:
    image: stefanscherer/whoami:linux-amd64-1.7.0
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:whoami.example.com"
      - "traefik.port=8080"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
