version: '3.6'

services:

  app:
    image: mriedmann/humhub:1.3.8
    restart: always
    networks:
      - proxy
      - humhub-db
    labels:
      - "traefik.enable=true"
      - "traefik.backend=${SUBDOMAIN}"
      - "traefik.frontend.rule=Host:${SUBDOMAIN}.${DOMAIN}"
      - "traefik.port=80"
      - "traefik.docker.network=proxy"
    depends_on:
      - db
    volumes:
      - "./data/app/config:/var/www/localhost/htdocs/protected/config"
      - "./data/app/uploads:/var/www/localhost/htdocs/protected/uploads"

  db:
    image: mariadb:10.2
    environment:
     - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
     - MYSQL_DATABASE=humhub
    restart: always
    volumes:
      - ./data/db/:/var/lib/mysql
    networks:
      - humhub-db

networks:
  humhub-db: {}
  proxy:
    external: true
